import { useEffect } from "react";
import { useDispatch } from "react-redux";
import Head from "next/head";
import { setAllRates } from "../redux/actions";
import Layout from "../components/Layout";
import { fetchData } from "../services/fetchData";

export const getStaticProps = async () => {
  const res = await fetch("https://api.coindesk.com/v1/bpi/currentprice.json");
  const data = await res.json();

  if (res.status !== 200) {
    console.error(data);
    throw new Error("Failed to fetch API");
  }

  return {
    props: {
      rates: Object.values(data.bpi),
    },
    revalidate: 10,
  };
};

export default function Home({ rates }) {
  const dispatch = useDispatch();
  dispatch(setAllRates(rates));

  useEffect(() => {
    setInterval(async () => {
      const data = await fetchData();
      dispatch(setAllRates(Object.values(data.bpi)));
    }, 20000);
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout />
    </>
  );
}
